### ISSUE TITLE
Implement GitHubReleaseChecker Action

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubReleaseChecker#1]
### I have done the items below . . .

- [X] I have created a title but left the 🚧 emoji behind.

### Description

Create a new **GitHub Action** that can check to see if a **GitHub Release** for a particular version has already been done.
- Purpose: Used to avoid performing a release if a release has already been performed.

Refer to Refer to this [GitHub Documentation](https://docs.github.com/en/rest/releases/releases) for more info about the REST API

### Acceptance Criteria

**This issue is finished when:**
- [ ] Repo created
- [ ] Basic empty project created
- [ ] Use the GitHub C# sample project below:
  - [NETGitHubActionSample](https://github.com/KinsonDigital/NETGitHubActionSample)
- [ ] The action will send back an output named `release-exists` of `true` or `false` signifying if the release already exists.
- [ ] Use the C# HTTP client [Rest Sharp](https://github.com/restsharp/RestSharp)
- [ ] This action will have the inputs below:
  - [ ] Repo owner
  - [ ] Repo name
  - [ ] Release Name
  - [ ] Tag Name

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project

**Comment by kselena** [comment]
The task below does not apply anymore.  This file is managed at the organization level now.
- [ ] Project repo setup for contributions and `FUNDING.yml` added to project
